/* tslint:disable */
/* eslint-disable */
/**
 * Sample API using Fastify and Zod.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetUserReply
 */
export interface GetUserReply {
  /**
   *
   * @type {string}
   * @memberof GetUserReply
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof GetUserReply
   */
  email: string;
}

/**
 * Check if a given object implements the GetUserReply interface.
 */
export function instanceOfGetUserReply(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "name" in value;
  isInstance = isInstance && "email" in value;

  return isInstance;
}

export function GetUserReplyFromJSON(json: any): GetUserReply {
  return GetUserReplyFromJSONTyped(json, false);
}

export function GetUserReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserReply {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
    email: json["email"],
  };
}

export function GetUserReplyToJSON(value?: GetUserReply | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    email: value.email,
  };
}
