/* tslint:disable */
/* eslint-disable */
/**
 * Sample API using Fastify and Zod.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserSchemasGetUserReply } from './UserSchemasGetUserReply';
import {
    UserSchemasGetUserReplyFromJSON,
    UserSchemasGetUserReplyFromJSONTyped,
    UserSchemasGetUserReplyToJSON,
} from './UserSchemasGetUserReply';

/**
 * 
 * @export
 * @interface UserSchemas
 */
export interface UserSchemas {
    /**
     * 
     * @type {UserSchemasGetUserReply}
     * @memberof UserSchemas
     */
    getUserReply?: UserSchemasGetUserReply;
}

/**
 * Check if a given object implements the UserSchemas interface.
 */
export function instanceOfUserSchemas(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserSchemasFromJSON(json: any): UserSchemas {
    return UserSchemasFromJSONTyped(json, false);
}

export function UserSchemasFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSchemas {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'getUserReply': !exists(json, 'getUserReply') ? undefined : UserSchemasGetUserReplyFromJSON(json['getUserReply']),
    };
}

export function UserSchemasToJSON(value?: UserSchemas | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'getUserReply': UserSchemasGetUserReplyToJSON(value.getUserReply),
    };
}

