/* tslint:disable */
/* eslint-disable */
/**
 * Sample API using Fastify and Zod.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSchemasGetUserReply
 */
export interface UserSchemasGetUserReply {
    /**
     * 
     * @type {string}
     * @memberof UserSchemasGetUserReply
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserSchemasGetUserReply
     */
    email: string;
}

/**
 * Check if a given object implements the UserSchemasGetUserReply interface.
 */
export function instanceOfUserSchemasGetUserReply(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function UserSchemasGetUserReplyFromJSON(json: any): UserSchemasGetUserReply {
    return UserSchemasGetUserReplyFromJSONTyped(json, false);
}

export function UserSchemasGetUserReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSchemasGetUserReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
    };
}

export function UserSchemasGetUserReplyToJSON(value?: UserSchemasGetUserReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
    };
}

