/* tslint:disable */
/* eslint-disable */
/**
 * Sample API using Fastify and Zod.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { GetUserReply } from "../models";
import { GetUserReplyFromJSON, GetUserReplyToJSON } from "../models";

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   */
  async userGetUserGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetUserReply>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/user/get-user`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => GetUserReplyFromJSON(jsonValue));
  }

  /**
   */
  async userGetUserGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserReply> {
    const response = await this.userGetUserGetRaw(initOverrides);
    return await response.value();
  }
}
