// Generated by Wrangler on Mon Apr 22 2024 15:19:19 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	KV: KVNamespace;
	KV_SWR: KVNamespace;
}
