// Generated by Wrangler on Tue Apr 23 2024 19:55:40 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  KV_WEB_NEXT: KVNamespace;
}
