// Generated by Wrangler on Wed Apr 24 2024 20:12:57 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	KV_WEB_NEXT: KVNamespace;
}
